### ISSUE TITLE
Custom Backgrounds

### ISSUE THREAD

**Issue by sbates-idrc** [codelearncreate/c2lc-coding-environment#413]
# Tasks

- [x] Update the Scene description to use the new character description
  - The Scene still has logic to support the character being out of bounds, we can remove that now
- [x] Add a non-visible heading to the tile panel
  - "Custom Background Design"
- [x] When in custom background edit mode, don’t change the starting position when the character is moved with the positioning controls
- [x] Grayscale and high contrast themes
  - [x] Tile colours
  - [x] Wall tile image
  - [x] Paint brush icon
- [x] Change the icon for the delete/blank tile in the tile panel to an eraser
  - [x] `aria-label:` "custom background eraser"
- [x] Change the label for the edit mode toggle switch to "custom background design mode"
- [x] Implement hover for the brush icon button in the positioning controls (the `IconButton` hover doesn’t currently work because the brush icon SVG includes the background)
- [x] Change the Grayscale selection and focus outline colours for the tile panel to be consistent with other parts of the UI (#505862)
- [x] Add new tiles for the gem, gold, and treats
- [x] Update the `aria-label` for the paint brush in the positioning controls
  - When no tile is selected: button is disabled, with label “set the custom background square” 
  - When the eraser is selected: "erase"
  - When a non-eraser tile is selected: "set \<description of selected tile\>", such as "set light blue" or "set wall"
- [x] Update the `aria-label` for the paintbrush
  - No selection: "paint background square" and disabled
  - Eraser: "erase square"
  - Non-eraser selected: "paint \<description\>" such as "paint light blue", "paint wall"
- [x] Update the character description
  - Current: "the spaceship is at column C, row 1 facing right on the Moon"
  - New: “at C1 on the moon facing right”
- [x] Update the Custom Background design mode cursor
- [x] Change the default mode to support screen reader discovery
  - [x] Tiles have behaviour: no
  - [x] Change the mechanism for setting the starting position and update the starting position marker
    - [x] Do not change the starting position when the character is moved
    - [x] Set the starting position by clicking on the button in the middle of the positioning controls, when not in design mode (no longer show the character icon in the positioning controls, the new button replaces it)
  - [x] Update the starting position marker to match the new button in the positioning controls
- [x] Update the control for switching into and out of custom background design mode
- [x] Add a status message to describe square behaviour (such as hitting a wall), only show the most recent message
  - [x] Pause the program when it encounters a wall
- [x] When the character hits the edge of the scene, display a message and pause the program (as for hitting a wall)
- [x] Add a shortcut for setting the starting position
  - [x] Add the shortcut, including updating the documentation
  - [x] Add a cell to our Grid 3 gridset for the new shortcut

# Moved to separate issues

- #419
- #420
- #421
- #422
- #423
- #424
- #425
- #426
- #427
- #428
- #429

# Design

- [x] Colors and patterns for greyscale and high contrast
- [x] Grayscale version of the paintbrush
- [x] Create an icon for the eraser tile
- [x] Tooltips for the tiles in the tile panel, describing the tile behaviour
- [x] Change the colour of the drawn line for high contrast mode so that it is visible against the custom background colours
- [x] Reach out to screen reader users to discuss contextual information
  - We currently read a description of what is under the character, but what about tiles that have behaviour? Such as a wall, or a teleportation square. How would a screen reader user know where a wall is (when not in edit mode)?
  - Would contextual information be generally useful? Not just for tiles with behaviour. For example if you are on D5 on the Atlantic Canada background, would it be helpful to know that there is an iceberg above and a whale to the right?
  - Could we also ask about our current character description? Is it too verbose?
    - Example: "the spaceship is at column C, row 1 facing right on the Moon"
- [x] In the default mode, moving the character will no longer set the starting position, we need a new UI for setting the starting position
  - Potential UI: use the button in the middle of the character controls to set the starting point in default mode (similar to the paintbrush in design mode)
- [x] Update the Custom Background design mode cursor
  - Replace the character on the scene with a paintbrush on a transparent background with 4 right angles at the corners
  - Use different colours for the paintbrush and cursor corners
  - When the eraser is selected, show an eraser, and otherwise show a paintbrush
  - Update the icon in the positioning controls
- [x] Add status messages/alerts regarding cell behavior
  - Communicate status/alert messages once a user interacts with a cell with specific behavior. Ex. you ran to a wall / You are teleported from B2 to F6
- [x] Add a way to easily delete the whole custom background or to toggle it off/on
  - I just had a custom background in my Weavly that covered the whole background, but wanted to check what the Grocery Store background looked like. I needed to use the eraser to delete every single square.
- [x] Design of the right hand side and location of the edit mode toggle control
  - From the co-design notes: "The right side panel needs to be simplified as it’s getting too busy with different scene related features."

# Questions

- How to treat the scene orientation?
  - Are we looking from above or from the side?
  - We will come back to this after we have identified some behaviour tiles that we would like to add and consider the question then, when it is more concrete
- Should we block you from being able to set a tile with behaviour (such as a wall or lava) on the starting square?

**Comment by sepidehshahi** [comment]
@sbates-idrc I have updated the tile panels in the Figma file and the Gray and High Contrast themes are ready for your review: https://www.figma.com/file/5msi8IMap0LFe0XLFS9QKW/C2LC-Design-System?type=design&node-id=5694%3A14652&mode=design&t=m27S7woSjVt0qgmk-1

**Comment by sepidehshahi** [comment]
Here is the icon for the eraser. Please review and let me know your thoughts: https://www.figma.com/file/5msi8IMap0LFe0XLFS9QKW/C2LC-Design-System?type=design&node-id=5726%3A8708&mode=design&t=m27S7woSjVt0qgmk-1

**Comment by sepidehshahi** [comment]
@sbates-idrc Here are the colours for the custom background design panel for different themes: 

Colours-Default
- Black#1E1E1E
- White#FFFFFF
- Gray#9DA4AF
- Brown#775034
- Red#F75322
- Orange#ED972C
- Yellow#F1D05B
- Green#52BD76
- Light blue#5CBCD1
- Dark Blue#416CA7
- Purple#A46BB8
- Pink#DF86CB
- Tile outline#4C9990

Colours-Gray scale
- Black#505862
- White#FFFFFF
- Gray#B9BEC6
- Brown#A48E7F
- Red#E6B09F
- Orange#DCC09D
- Yellow#E9DDB5
- Green#A0C2AC
- Light blue#B1D2DA
- Dark Blue#7B93B5
- Purple#AB93B4
- Pink#DCC6D7
- Tile outline#67717E

Colours-High Contrast
- Black#1E1E1E
- White#FFFFFF
- Gray#B4B4B4
- Brown#B5651D
- Red#FF3A00
- Orange#FFA500
- Yellow#FFF500
- Green#00FF57
- Light blue#00F0FF
- Dark Blue#0000FF
- Purple#AD00FF
- Pink#FF00C5
- Tile outline#FFFFFF

**Comment by sbates-idrc** [comment]
Potential designs for the line drawing in high contrast theme:

![Screenshot 2023-09-20 at 11 12 29 AM](https://github.com/codelearncreate/c2lc-coding-environment/assets/80360967/a7f80937-45fc-4fc1-9105-369a84676a78)

![Screenshot 2023-09-20 at 11 24 58 AM](https://github.com/codelearncreate/c2lc-coding-environment/assets/80360967/b1b667cd-d47d-4684-88c1-52174a69969d)

**Comment by sbates-idrc** [comment]
Fixed in bde8c4440a5cc48367c427d4550c2585df10ee57
